name: "🐛 バグ報告 (Bug Report)"
description: "Cairnsドキュメント、スキーマ、CI/CD、静的サイト等の不具合を報告します。"
title: "🐛 [バグ内容の要約]"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **バグ報告ありがとうございます！**
        問題を正確に把握するため、以下の項目について可能な範囲で詳細にご記入ください。
  - type: input
    id: related-doc
    attributes:
      label: "関連ドキュメント/ファイル"
      description: "影響を受けるCairnsドキュメントID、スキーマファイル、CIスクリプト等のパスを記載してください。"
      placeholder: "例: l2-design-principles.md, schema/common-defs.schema.json"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "バグの説明"
      description: "どのような問題が発生していますか？"
      placeholder: "例: l2-design-principles.md の core_principles 内 'srp' の summary が途中で切れている。"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "再現手順"
      description: "この問題を再現させるための具体的な手順を記載してください。"
      placeholder: |
        1. 静的サイトの /docs/l2-design-principles を開く
        2. Core Principles セクションを確認する
        3. SRP の説明文を見る
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "期待される動作"
      description: "本来はどうあるべきだと期待しますか？"
      placeholder: "例: SRP の summary が最後まで正しく表示される。"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "実際の動作"
      description: "実際にはどうなっていますか？"
      placeholder: "例: summary が '... focused on a single task' で途切れている。"
    validations:
      required: true
  - type: textarea
    id: screenshots-logs
    attributes:
      label: "スクリーンショット/ログ (任意)"
      description: "問題の理解を助けるスクリーンショットやログがあれば、ここに貼り付けてください。"
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: "環境情報 (任意)"
      description: "問題が発生した環境（ブラウザ、OSなど）を記載してください。"
      placeholder: "例: Chrome 110, Windows 11"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
        **Note:** 貢献に関する詳細は [`l0-contribution-guide.md`](./docs/L0-library-overview/l0-contribution-guide.md) を参照してください。